export const assetPaths = {
  logo: "/images/logo-efagram.webp",
  logoWhite: "/images/logo-efagram-white.webp",
  hero: "/images/paisaje-forestal-efagram.webp",
  eucalyptus: "/images/plantacion-eucalipto.webp",
  harvester: "/images/operacion-harvester.webp",
  pineDetail: "/images/detalle-pino-brumoso.webp",
  pineCloseup: "/images/detalle-pino.webp",
  forestCanopy: "/images/dosel-bosque.webp",
  verticalForest: "/images/bosque-pinos-vertical.webp",
  logoCompleto: "/images/LogoCompleto.webp",
  zonaInfluencia: "/images/ZonaInfluencia.webp",
  harvester2: "/images/Harvester2.webp",
  plantacionAerea: "/images/plantacion desde el aire.webp",
  plantacionEucalipto: "/images/plantacion eucalipto.webp",
  plantacionEucalipto2: "/images/plantacion-eucalipto 2.webp",
  equipo: "/images/Equipo.webp",
  forestal: "/images/Forestal.webp",
  forestal2: "/images/Forestal2.webp",
  fw: "/images/fw.webp",
  paisaje: "/images/paisaje.webp",
  alturasSst: "/images/AlturasSst.webp",
  harvester3: "/images/Harvester3.webp",
};
